---
slurm_packages:
  - slurmd
  - devel
  - libpmi

slurm_role: compute

install_packages: []

mpi_packages:
  oracle:
    - mpich
    - openmpi
  google: []
  aws: []

monitoring_role: client

ldap_hostname: "{{ ansible_local.citc.ldap_hostname }}"
