---
slurm_packages:
  - slurmd
  - devel
  - pmi
  - pmi-devel

slurm_role: compute

install_packages:
  - python3-requests
  - jq

mpi_packages:
  oracle:
    - mpich
    - openmpi
  google: []
  aws: []

monitoring_role: client

ldap_hostname: "{{ ansible_local.citc.ldap_hostname }}"
