---

- name: Create Spack Directory
  file:
    path: /mnt/shared/spack
    owner: citc
    group: citc
    state: directory
    mode: 0775

- name: Clone Spack
  git:
    repo: https://github.com/spack/spack.git
    dest: /mnt/shared/spack
    version: v0.16.0
    depth: 1
  become_user: citc

- name: Apply Spack configurations
  copy:
    dest: /mnt/shared/spack/etc/spack/config.yaml
    content: |
      config:
        db_lock_timeout: 30
    mode: 0644
    owner: citc
    group: citc

- name: Init Spack DB
  command: /mnt/shared/spack/bin/spack reindex
  become_user: citc

- name: Create Benchmark Dataset Directory
  file:
    path: /mnt/shared/benchmarks
    owner: citc
    group: citc
    state: directory
    mode: 0775

- name: Add Spack to default shells
  copy:
    dest: /etc/profile.d/99-spack.sh
    content: |
      . /mnt/shared/spack/share/spack/setup-env.sh
    owner: root
    mode: u=rwx,g=rx,o=rx
    force: no
