---

- hosts: compute
  tasks:
    - name: disable SELinux
      selinux:
        state: disabled

- hosts: compute
  roles:
    - citc_user
    - filesystem
    - ssh
    #- security_updates
    - ntp
    - sssd
    - lmod
    - packages
    - devtoolset
    - mpi
    - slurm
    - spack_compute
    - monitoring

- hosts: compute
  tasks:
    - name: Set Proxy
      copy:
        dest: /etc/profile.d/98-proxy.sh
        content: "export http_proxy=http://{{ mgmt_hostname }}:3128"
        mode: 0644
