---

- hosts: compute
  tasks:
    - name: disable SELinux
      selinux:
        state: disabled

- hosts: compute
  roles:
    - citc_user
    - filesystem
    - ssh
    #- security_updates
    - ntp
    - sssd
    - lmod
    - packages
    - devtoolset
    - mpi
    - slurm
    - spack_compute
    - monitoring
