---

- name: install roles
  hosts: management
  tasks:
    - name: Download required roles
      command: ansible-galaxy install -r requirements.yml
      register: galaxy_result
      changed_when: '"was installed successfully" in galaxy_result.stdout'
      become: false
      delegate_to: localhost

- name: finisher script
  hosts: management
  tasks:
    - name: copy over finisher script
      template:
        src: roles/finalise/templates/finish.py.j2
        dest: /usr/local/bin/finish
        mode: 0755
    - name: set motd
      copy:
        content: |
          ######################

          Welcome to the cluster
          Please now create users and define the number of nodes you want.

          ######################
        dest: /etc/motd
        mode: u=rw,g=r,o=r

- name: common
  hosts: all
  tags: common
  roles:
    - citc_user
    - filesystem
    - ssh
    - security_updates
    - ntp
    - ldap
    - sssd
    - python
    - users
    - mysql
    - slurm
    - proxy
    - spack
    - packer
  tasks:
    - name: copy SSH public keys to slurm account
      copy:
        src: "{{ admin_key_path }}"
        dest: /home/slurm/opc_authorized_keys
        owner: slurm
        group: slurm
        mode: 0600

- name: finalise
  hosts: all
  tags: finalise
  roles:
    - finalise
    - clustershell
    - packages
    - devtoolset
    - mpi
    - spack_compute
    - debug_tools
    - lmod
    - instance_limits

- name: Update Service Node
  hosts: management
  tasks:
  - name: Make etc
    file:
      path: /mnt/shared/etc
      state: directory
  - name: Make bin
    file:
      path: /mnt/shared/bin
      state: directory
  - name: Make sbin
    file:
      path: /mnt/shared/sbin
      state: directory
  - name: Install Command and Control Config
    copy:
      src: /tmp/cluster_control/cluster_control.json
      dest: /mnt/shared/etc/cluster_control.json
      mode: 0444
  - name: Install Command and Control Updater
    copy:
      src: /tmp/cluster_control/update_service_db
      dest: /mnt/shared/bin/update_service_db
      mode: 0755
  - name: Install Command and Control Receiver
    copy:
      src: /tmp/cluster_control/run_command
      dest: /mnt/shared/sbin/run_command
      mode: 0755
  - name: Install Python dependencies
    pip:
      name:
        - google-api-python-client
        - google-cloud-storage
        - boto3
        - pexpect
      virtualenv:  /opt/cloud_sdk
