---

- name: Install Squid
  yum:
    name:
      - squid

- name: enable Squid
  service:
    name: squid
    state: started
    enabled: yes

- name: Set Proxy Env var
  copy:
    dest: /etc/profile.d/98-proxy.sh
    content: "export http_proxy=http://{{ mgmt_hostname }}:3128"
    mode: 0644
