---
- name: install common tools
  pip:
    name:
      - PyYAML
      - git+https://github.com/brandenm-nag/python-citc.git@c398_master
    virtualenv: /opt/cloud_sdk
    virtualenv_command: "{{ python_venv }}"
  register: cloud_sdk_venv

- name: install watchdog service
  template:
    src: citc-watchdog.service.j2
    dest: /usr/lib/systemd/system/citc-watchdog.service
    mode: 0755

- name: create citc config dir
  file:
    path: /etc/citc
    state: directory
    owner: slurm
    group: slurm
    mode: 0755

- name: copy mgmt_shape.yaml
  copy:
    src: /home/opc/mgmt_shape.yaml
    dest: /etc/citc/mgmt_shape.yaml
    owner: slurm
    group: slurm
    mode: 0744
  when: '"/home/opc/mgmt_shape.yaml" is exists'

- name: copy shapes.yaml
  copy:
    src: /tmp/shapes.yaml
    dest: /etc/citc/shapes.yaml
    owner: slurm
    group: slurm
    mode: 0744
  when: '"/tmp/shapes.yaml" is exists'

- name: copy startnode.yaml
  copy:
    src: /tmp/startnode.yaml
    dest: /etc/citc/startnode.yaml
    owner: slurm
    group: slurm
    mode: 0744

- name: configure startnode script
  copy:
    src: startnode.py
    dest: /usr/local/bin/startnode
    mode: 0755

- name: configure stopnode script
  copy:
    src: stopnode.py
    dest: /usr/local/bin/stopnode
    mode: 0755

- name: configure update_config script
  copy:
    src: update_config.py
    dest: /usr/local/bin/update_config
    mode: 0755

- name: install kill_all_nodes script
  copy:
    src: kill_all_nodes.sh
    dest: /usr/local/bin/kill_all_nodes
    mode: u=rwx,g=rwx,o=rx

# TODO Replace this with openssh_keypair when we use Ansible 2.8
- name: generate SSH host keys for compute nodespace
  shell: ssh-keygen -t {{ item.type }} -b {{ item.size }} -f {{ item.path }} -N "" < /dev/null
  args:
    creates: "{{ item.path }}"
  with_items:
    - {"type": "ed25519", "size": 4096, "path": "/home/slurm/ssh_host_ed25519_key"}
    - {"type": "rsa", "size": 4096, "path": "/home/slurm/ssh_host_rsa_key"}
    - {"type": "ecdsa", "size": 521, "path": "/home/slurm/ssh_host_ecdsa_key"}

- name: set ownership of host files
  file:
    path: "{{ item }}"
    owner: slurm
    group: slurm
  loop:
    - /home/slurm/ssh_host_ed25519_key
    - /home/slurm/ssh_host_ed25519_key.pub
    - /home/slurm/ssh_host_rsa_key
    - /home/slurm/ssh_host_rsa_key.pub
    - /home/slurm/ssh_host_ecdsa_key
    - /home/slurm/ssh_host_ecdsa_key.pub

- name: load the startnode config
  include_vars:
    file: /etc/citc/startnode.yaml
    name: startnode_config

- name: create cloud-init bootstrap script
  copy:
    content: |
      #! /bin/bash

      date

      cat > /etc/ssh/ssh_host_ecdsa_key << EOF
      {{ lookup('file', '/home/slurm/ssh_host_ecdsa_key') }}
      EOF
      cat > /etc/ssh/ssh_host_ecdsa_key.pub << EOF
      {{ lookup('file', '/home/slurm/ssh_host_ecdsa_key.pub') }}
      EOF
      cat > /etc/ssh/ssh_host_rsa_key << EOF
      {{ lookup('file', '/home/slurm/ssh_host_rsa_key') }}
      EOF
      cat > /etc/ssh/ssh_host_rsa_key.pub << EOF
      {{ lookup('file', '/home/slurm/ssh_host_rsa_key.pub') }}
      EOF
      cat > /etc/ssh/ssh_host_ed25519_key << EOF
      {{ lookup('file', '/home/slurm/ssh_host_ed25519_key') }}
      EOF
      cat > /etc/ssh/ssh_host_ed25519_key.pub << EOF
      {{ lookup('file', '/home/slurm/ssh_host_ed25519_key.pub') }}
      EOF
      chmod 600 /etc/ssh/ssh_host_*
      chmod 644 /etc/ssh/ssh_host_*.pub

      {% if ansible_local.citc.csp == "aws" %}
      yum install -y epel-release
      dnf install -y jq
      python3 -m pip install awscli
      region=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output '.region')
      instanceid=$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)
      name=$(/usr/local/bin/aws ec2 describe-tags --region=${region} --filters "Name=resource-id,Values=${instanceid}"\
                                                  --output text --query 'Tags[?Key==`Name`].Value')
      hostnamectl set-hostname ${name}
      {% endif %}

      # Ensure that slurmd is running at this point
      systemctl start slurmd

      date
    dest: /home/slurm/bootstrap.sh
    owner: slurm
    mode: u=rw,g=r,o=

- name: copy list_nodes script
  copy:
    src: list_nodes.sh
    dest: /usr/local/bin/list_nodes
    mode: 0755

- name: start and enable service citc-watchdog
  service:
    name: citc-watchdog
    state: started
    enabled: yes
