---
- name: Ensure unzip is installed.
  package: name=unzip state=present

- name: Download and unarchive Packer.
  unarchive:
    src: https://releases.hashicorp.com/packer/1.6.0/packer_1.6.0_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/packer
    mode: u=rwx,g=rx,o=rx

- name: set permissions on packer
  file:
    path: /usr/local/bin/packer
    mode: u=rwx,g=rx,o=rx

- name: create packer directory
  file:
    path: /etc/citc/packer/
    state: directory
    mode: 0755

- name: copy in packer build files
  copy:
    src: all.pkr.hcl
    dest: /etc/citc/packer/all.pkr.hcl
    mode: u=rw,g=r,o=r

- name: load the startnode config
  include_vars:
    file: /etc/citc/startnode.yaml
    name: startnode_config

- name: copy in packer ansible run script
  template:
    src: run_ansible.sh.j2
    dest: /etc/citc/packer/run_ansible.sh
    owner: root
    mode: u=rwx,g=,o=

- name: copy in packer kernel-update
  copy:
    src: update_kernel.sh
    dest: /etc/citc/packer/update_kernel.sh
    owner: root
    mode: u=rwx,g=rx,o=rx

- name: copy in packer gvnic builder
  copy:
    src: update_kernel.sh
    dest: /etc/citc/packer/install_gvnic.sh
    owner: root
    mode: u=rwx,g=rx,o=rx

- name: copy in packer extra run script template (no force overwrite)
  copy:
    src: compute_image_extra.sh
    dest: /home/citc/compute_image_extra.sh
    force: no
    owner: citc
    group: citc
    mode: u=rw,g=rw,o=

- name: copy in config
  template:
    src: variables.pkrvars.hcl.j2
    dest: /etc/citc/packer/variables.pkrvars.hcl
    mode: u=rw,g=r,o=r

- name: copy in packer run script
  template:
    src: run-packer.sh.j2
    dest: /usr/local/bin/run-packer
    mode: u=rwx,g=rx,o=rx

- name: run packer to build first image
  command: /usr/local/bin/run-packer
  register: packer_result
  changed_when: "packer_result.rc == 0"
  failed_when: "packer_result.rc != 0"
  tags: packer
