---

- name: check if powertools repo is already enabled
  shell: |
    set -o pipefail
    dnf -q repolist --enabled powertools | grep -i powertools  # noqa 301
  changed_when: false
  register: powertools
  failed_when: powertools.rc == 2
  when: ansible_local.citc.csp != "oracle"

- name: enable powertools module
  command: dnf config-manager --set-enabled powertools
  when:
    - ansible_local.citc.csp != "oracle"
    - powertools.rc != 0

- name: install Lmod
  package:
    name: Lmod
    state: present

- name: install lmod config
  copy:
    dest: /etc/profile.d/10-modules.sh
    content: MODULEPATH={{ software_install_dir }}/manual_modules/
    mode: u=rw,g=r,o=r
