---

- name: install python38
  package:
    name: python38

- name: set Python path fact
  set_fact: python_bin=/usr/bin/python3.8
- name: set venv path fact
  set_fact: python_venv="{{ python_bin }} -m venv"
