---

- name: Prepare
  hosts: all
  tasks:
    # The packer role depends on files being put in the citc user's home dir,
    - name: put key file in correct location
      copy:
        content: 'key contents...'
        dest: "{{ admin_key_path }}"
        mode: u=rw,g=r,a=r
    - name: run citc_user roles for dependency
      include_role:
        name: citc_user

    - name: startnode config  # Put there by Terraform usually
      copy:
        content: |
          csp:
          cluster_id: example
          ansible_repo: https://github.com/clusterinthecloud/ansible.git
          ansible_branch: 6
        dest: /tmp/startnode.yaml
        mode: u=rw,g=r,o=r

    - name: ca cert  # Put there by the `ldap` role
      copy:
        content: |
          some dummy test pretending to be
          a certificate
        dest: "{{ ca_cert }}"
        mode: u=rw,g=r,o=r

    - name: make ansible config dir
      file:
        path: /etc/ansible
        state: directory
        mode: a=rw,o+x
    - name: make ansible facts dir
      file:
        path: /etc/ansible/facts.d
        state: directory
        mode: a=rw,o+x
    - name: create local citc.fact file  # Put there by Terraform usually
      copy:
        content: |
          {"csp":"example", "fileserver_ip":"10.0.0.1", "mgmt_hostname":"mgmt"}
        dest: /etc/ansible/facts.d/citc.fact
        mode: u=rw,g=r,o=r
