---

- name: Install Development Tools
  yum:
    name: "@Development-tools"
    state: present

- name: install gcc-toolset
  package:
    name: gcc-toolset-9

- name: install gfortran
  package:
    name: gcc-gfortran

- name: install cmake
  package:
    name: cmake
